---
abstract: 'Parse SSH2 public keys in either SECSH or OpenSSH format.'
author:
  - 'Nathan Marley <nathan.marley@gmail.com>'
build_requires:
  File::Slurp: 0
  File::Temp: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-SSH2-PublicKey
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  MIME::Base64: 0
  Moo: 0
  Test::More: 0
  autodie: 0
version: 0.01
